services:
  db:
    image: mysql:8.2.0
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-password}
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    stdin_open: true
  
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-password}
      MYSQL_HOST_NAME: db
    depends_on:
      db:
        condition: service_started
    tty: true
    stdin_open: true

  web:
    build:
      context: web
      dockerfile: Dockerfile
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend/api/tmp/sockets:/app/tmp/sockets
      - ./frontend/app/dist:/app/public
    environment:
      TZ: Asia/Tokyo
    ports:
      - 80:80
    depends_on:
      backend:
        condition: service_started
    tty: true
    stdin_open: true

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
    environment:
      TZ: Asia/Tokyo
      VITE_APP_API_BASE: ${APP_API_BASE:-http://localhost:3000}
    tty: true
    stdin_open: true